name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os   : [ubuntu-latest]
        scala: [2.12.15]
        java : [8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: Cache
        uses: coursier/cache-action@v5

      - name: Test
        run: sbt ++${{ matrix.scala }} validate
